<a href="https://colab.research.google.com/github/EfeTascioglu/Machine-Learning-with-PyTorch/blob/master/Pytorch_learn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch
import torchvision
import torch.nn as nn
import torch.nn.functional as F

In [0]:
"""
from IPython.core.debugger import set_trace

def f(x):
  res = x * x
  set_trace()
  return res

x = torch.randn(1, requires_grad = True)
y = f(x)
"""

In [0]:
"""
from collections import OrderedDict


layers = OrderedDict([
    ('conv1', nn.Conv2d(in_channels=1, out_channels=20, kernel_size=5))
])
model = nn.Sequential(layers)
"""

_like means takes in another Tensor instead of sizes

randn -> mean 0, variance 1

randint -> (low, high, sizes)

randint_like(x, low, high)

In [5]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.8712,  0.0820, -1.0769],
        [ 0.1931,  0.4399, -0.6486],
        [ 0.2433, -0.9184,  0.5804],
        [ 0.9115,  1.4057, -0.9224],
        [-0.7652,  0.5908,  1.1210]])


In [6]:
print(x.size())

torch.Size([5, 3])


In [0]:
y = torch.rand(5,3)

In [15]:

torch.add(x, y)

#OR

result = torch.empty(5,3)
torch.add(x, y, out=result)
#this keeps tensor3 sizes

#OR

x + y

#OR

x.add_(y)
#x is already added

#All work


tensor([[2.8677, 3.0073, 0.6395],
        [4.6987, 5.1678, 3.4201],
        [0.2932, 4.0846, 1.1373],
        [5.8390, 1.5760, 2.5463],
        [4.2492, 3.6848, 2.4318]])

In [16]:
print(x)

tensor([[2.8677, 3.0073, 0.6395],
        [4.6987, 5.1678, 3.4201],
        [0.2932, 4.0846, 1.1373],
        [5.8390, 1.5760, 2.5463],
        [4.2492, 3.6848, 2.4318]])


In [17]:
print(x[:, 1]) # prints collumn 1 (e.g 0, 1, 2)


tensor([3.0073, 5.1678, 4.0846, 1.5760, 3.6848])


In [20]:
x = torch.randn(4,4)
print(x)
y = x.view(16) # rearange/resize
print(y)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
# for example, since there is 16 values, 16/8 = 2   (-1 = 2)
print(z)
print(x.size(), y.size(), z.size())

tensor([[ 1.2036,  0.3352, -0.8797,  0.1856],
        [ 1.5617, -1.9622,  0.3835,  1.8229],
        [-0.3723,  0.6476,  1.1635,  1.9080],
        [-0.2063, -0.8104,  0.4370,  0.4309]])
tensor([ 1.2036,  0.3352, -0.8797,  0.1856,  1.5617, -1.9622,  0.3835,  1.8229,
        -0.3723,  0.6476,  1.1635,  1.9080, -0.2063, -0.8104,  0.4370,  0.4309])
tensor([[ 1.2036,  0.3352, -0.8797,  0.1856,  1.5617, -1.9622,  0.3835,  1.8229],
        [-0.3723,  0.6476,  1.1635,  1.9080, -0.2063, -0.8104,  0.4370,  0.4309]])
torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])
